sample_file: 'sample_reads.tsv'
ref_ftp: 'https://ftp.ensembl.org/pub/release-110/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz'
contig_filter_length: '1500'
contig_gene_length: '100'

